'use strict';
// Presentation only. Every shortcut uses an existing role endpoint.
const {patternMarkup, glyph} = require('./govo_ui_pattern_v32');
const CONFIG = {
 merchant: {label:'Merchant',home:'/merchant/dashboard',hint:'Your shop, products and customer orders.',links:[
 ['Dashboard','/merchant/dashboard','home_nav'],['Orders','/merchant/dashboard#orders','orders'],['Products','/merchant/products','shops'],['Shop profile','/merchant/dashboard#profile','account'],['Availability','/merchant/dashboard#profile','settings'],['Support','/merchant/support','support'],['Application status','/dashboard/merchant','shield'],['Marketplace','https://app.govoexpress.com/shops','search'],['Track order','https://app.govoexpress.com/track','track']],extra:[['Logout','/merchant/logout','account']]},
 rider: {label:'Rider',home:'/rider/dashboard',hint:'Assigned work, delivery updates and your profile.',links:[
 ['Dashboard','/rider/dashboard','home_nav'],['New jobs','/rider/jobs','orders'],['Active delivery','/rider/active','delivery'],['History','/rider/history','history'],['My profile','/rider/dashboard#profile','account'],['Availability','/rider/dashboard#profile','settings'],['Support','/rider/support','support'],['Application status','/dashboard/rider','shield'],['Track order','https://app.govoexpress.com/track','track']],extra:[['Logout','/rider/logout','account']]},
 admin: {label:'Admin',home:'/admin/os',hint:'Orders, dispatch, partners and operations.',links:[
 ['Dashboard','/admin/os','home_nav'],['Orders','/admin/orders','orders'],['Dispatch','/admin/dispatch','delivery'],['Service requests','/admin/service-requests','requests'],['Merchants','/admin/leads?filter=all','shops'],['Riders','/admin/riders?filter=all','ride'],['Providers','/admin/providers?filter=all','services'],['Finance','/admin/finance','payment'],['Support inbox','/admin/support','support']],extra:[
 ['Command center','/admin/command','settings'],['Onboarding','/admin/onboarding','account'],['Task board','/admin/tasks','parcel'],['WhatsApp & calls','/admin/whatsapp','phone'],['QA','/admin/qa','shield'],['Launch checklist','/admin/launch-checklist','shield'],['Pilot','/admin/pilot','location'],['Partner CRM','/admin/pilot-crm','account'],['Reviews','/admin/reviews','gift'],['Notification templates','/admin/notify-templates','bell'],['Daily report','/admin/ops-daily-report','history'],['Summary draft','/admin/ops-summary-draft','parcel'],['Logout','/admin/logout','account']]}
};
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function link([label,href,icon],cls=''){return `<a class="${cls}" href="${href}">${glyph(icon)}<span>${label}</span></a>`;}
const CSS = `
.govo-os *,.govo-os *:before,.govo-os *:after{box-sizing:border-box}
.govo-os .govo-v28-header-row{display:flex;align-items:center;justify-content:space-between;gap:12px}
.govo-os .govo-master-brand{display:flex;align-items:center;gap:9px;min-width:0;text-decoration:none}.govo-os .govo-master-copy{display:flex;flex-direction:column;line-height:1.2;min-width:0}.govo-os .govo-master-copy strong{font-size:16px;font-weight:850;white-space:nowrap}.govo-os .govo-master-copy small{font-size:8px;margin-top:4px;font-weight:800;color:var(--os-active);letter-spacing:.08em}.govo-os .govo-inline-logo{width:60px;height:44px;display:grid;place-items:center;flex:none}.govo-os .govo-inline-logo img{width:100%;height:100%;object-fit:contain}
.govo-os .govo-role-actions{display:flex;gap:8px;flex:none}.govo-os .govo-role-actions :is(a,button){width:42px;height:42px;min-height:42px;display:grid;place-items:center;padding:0!important;border-radius:14px!important;text-decoration:none}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version]{--os-bg:#06141d;--os-panel:#102b34;--os-input:#071c25;--os-text:#f2fafb;--os-muted:#a8c8c9;--os-line:#87d6d52b;--os-active:#39e75f;--text:var(--os-text);--muted:var(--os-muted);--surface:var(--os-input);--border:var(--os-line);--primary:#51e482;--primaryText:#063322;--green:#39e75f;--green2:#19cff0;--gold:#19cff0;--ivory:var(--os-text);--ink:var(--os-text);background:radial-gradient(ellipse at 0 0,#0d302b,transparent 55%),var(--os-bg)!important;color:var(--os-text)!important}
html[data-theme=light] body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version]{--os-bg:#edf6f5;--os-panel:#fbfefd;--os-input:#f4faf8;--os-text:#17333b;--os-muted:#526e74;--os-line:#1b817d30;--os-active:#117f48;background:radial-gradient(ellipse at 0 0,#dcf3e7,transparent 55%),var(--os-bg)!important;color:var(--os-text)!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .app,html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .wrap,html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .v20-shell{width:auto!important;max-width:1500px!important;margin:0 auto!important;padding:0 24px 40px 266px!important;min-width:0}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-v28-header{position:relative!important;margin:0!important;padding:20px 0!important;z-index:45!important;box-shadow:none!important;background:transparent!important;border:0!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-role-menu,html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .admin-nav,html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .bottom-nav,html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .v20-bottom,html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-bottom-nav{display:none!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-os-rail{position:fixed;top:20px;bottom:20px;left:max(20px,calc((100vw - 1500px)/2 + 20px));width:218px;padding:20px 12px;overflow:auto;border:1px solid var(--os-line);border-radius:24px;background:var(--os-panel);z-index:80;scrollbar-width:thin}
.govo-os-rail .os-rail-title{padding:0 10px 18px;display:block;font-size:18px;font-weight:850;color:var(--os-text)}.govo-os-rail .os-rail-title small{display:block;margin-top:5px;font-size:11px;font-weight:600;color:var(--os-muted)}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-os-rail a{display:flex;align-items:center;gap:10px;min-height:44px;padding:8px 10px;margin:3px 0;border:1px solid transparent;border-radius:13px;color:var(--os-muted)!important;text-decoration:none!important;font-size:13px;font-weight:750;background:transparent!important}
.govo-os-rail .govo-v32-glyph{width:26px;height:26px;flex:none}.govo-os-rail .os-secondary{margin-top:14px;border-top:1px solid var(--os-line);padding-top:12px}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-os-rail a[aria-current],html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-os-dock a[aria-current]{background:color-mix(in srgb,var(--os-active) 13%,transparent)!important;color:var(--os-active)!important;border-color:color-mix(in srgb,var(--os-active) 35%,transparent)!important}
.govo-os-workspace{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:0 2px 18px}.govo-os-workspace .os-eyebrow{font-size:10px;text-transform:uppercase;letter-spacing:.13em;font-weight:850;color:var(--os-active)}.govo-os-workspace strong{display:block;color:var(--os-text);font-size:22px;line-height:1.3;margin-top:5px}.govo-os-workspace p{margin:4px 0 0!important;font-size:12px!important;color:var(--os-muted)!important;line-height:1.5!important}
.govo-os-launcher{border:1px solid var(--os-line);border-radius:22px;background:var(--os-panel);margin-bottom:20px;padding:0 16px 16px}.govo-os-launcher:not([open]){padding-bottom:0}.govo-os-launcher summary{cursor:pointer;padding:16px 0;font-weight:800;font-size:14px;color:var(--os-text);list-style:none;display:flex;align-items:center;justify-content:space-between}.govo-os-launcher summary::-webkit-details-marker{display:none}.govo-os-launcher summary::after{content:'+';font-size:22px;color:var(--os-active)}.govo-os-launcher[open] summary::after{content:'−'}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-os-apps{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:10px}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-os-apps a{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;gap:10px;min-height:114px;padding:14px 8px;border-radius:18px;background:linear-gradient(145deg,color-mix(in srgb,var(--os-active) 8%,var(--os-panel)),var(--os-input))!important;border:1px solid var(--os-line)!important;color:var(--os-text)!important;text-decoration:none!important;font-weight:800;font-size:13px;box-shadow:inset 0 1px 0 #ffffff12!important}
.govo-os .govo-os-apps .govo-v32-glyph{width:60px!important;height:60px!important;min-width:60px!important;min-height:60px!important;flex:none}.govo-os-apps span:last-child{overflow-wrap:anywhere;line-height:1.3}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(.card,.stat,.hero,.govo-premium-panel,.govo-premium-hero){background:var(--os-panel)!important;border:1px solid var(--os-line)!important;border-radius:22px!important;box-shadow:none!important;color:var(--os-text)!important;min-width:0;padding:20px!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(h1,h2,h3,h4,label,b,strong){color:var(--os-text)!important;text-shadow:none!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] h1{font-size:clamp(25px,3.5vw,36px)!important;line-height:1.2!important;letter-spacing:-.025em!important;margin:0 0 12px!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] h2{font-size:19px!important;line-height:1.4!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(p,.muted,.form-hint,.govo-form-note){color:var(--os-muted)!important;line-height:1.65!important;overflow-wrap:anywhere}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(.grid,.stats-grid){grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:14px!important;margin-bottom:20px}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .grid.two{grid-template-columns:repeat(2,minmax(0,1fr))!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .stat .value,html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .metric{font-size:30px!important;font-weight:850!important;color:var(--os-active)!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .stat .label{font-size:11px;letter-spacing:.05em;color:var(--os-muted)!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(input,select,textarea){background:var(--os-input)!important;color:var(--os-text)!important;border:1px solid var(--os-line)!important;border-radius:13px!important;min-height:46px;padding:12px!important;width:100%;max-width:100%;font-size:16px;box-shadow:none!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] input[type=hidden]{display:none!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] input:is([type=checkbox],[type=radio]){width:18px!important;min-height:18px!important;height:18px!important;accent-color:var(--os-active)}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(button,.btn,.govo-btn){min-height:44px;border-radius:13px!important;box-shadow:none!important;font-size:13px!important;line-height:1.4!important;padding:11px 15px!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(button,.btn,.govo-btn):not(.secondary):not(.reject):not(.theme-toggle){background:linear-gradient(135deg,#58e993,#35ce70)!important;color:#063322!important;border:1px solid #39e75f55!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(button.secondary,.btn.secondary,.govo-btn.secondary){background:var(--os-input)!important;color:var(--os-text)!important;border:1px solid var(--os-line)!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] button.reject{background:#9a3042!important;color:#fff!important}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(.detail-grid>div,.item-box,.activity-row){background:var(--os-input)!important;border-color:var(--os-line)!important;border-radius:14px!important;padding:14px!important;min-width:0;color:var(--os-text)!important}
.govo-os :is(.toolbar,.actions){gap:8px!important;align-items:center}.govo-os .detail-grid{gap:10px!important}.govo-os :is(.detail-grid span,.activity-row span,td){overflow-wrap:anywhere}.govo-os :is(.card,.hero,.stat,.govo-os-rail) a:focus-visible,.govo-os summary:focus-visible,.govo-os :is(input,select,textarea,button):focus-visible{outline:2px solid var(--os-active)!important;outline-offset:3px}
html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] table{width:100%;border-collapse:collapse;background:var(--os-panel)!important;color:var(--os-text)!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(th,td){border-bottom:1px solid var(--os-line)!important;padding:14px 12px!important;text-align:left;font-size:13px}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] th{background:var(--os-input)!important;color:var(--os-muted)!important;font-size:11px;text-transform:uppercase;letter-spacing:.04em}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(.govo-status-buttons,.rider-action-buttons,.merchant-action-buttons) button.active:not(.secondary):not(.reject):not(.theme-toggle){background:#19cff0!important;color:#06333b!important;outline:2px solid #19cff0;outline-offset:2px}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .role-status{background:color-mix(in srgb,var(--os-active) 15%,var(--os-input))!important;color:var(--os-active)!important;border:1px solid var(--os-line)}.govo-os-table{max-width:100%;overflow:auto;border-radius:16px;overscroll-behavior:contain}.govo-os-table:focus-visible{outline:2px solid var(--os-active)}
.govo-os-backdrop,.govo-os-dock,.os-close{display:none}.govo-os [id]{scroll-margin-top:20px}.govo-os-auth .govo-os-workspace{max-width:600px;margin:auto}.govo-os-auth .govo-os-launcher{display:none}.govo-os-auth .card:has(input[type=password]){max-width:600px;margin:20px auto!important}
@media(min-width:1000px){html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-role-actions button[aria-label=Menu]{display:none!important}.govo-os-auth .govo-os-rail{display:none!important}html body.govo-os.govo-os-auth .app{padding-left:24px!important;max-width:1000px!important}}
@media(max-width:999px){html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .app,html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .wrap,html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .v20-shell{width:100%!important;padding:0 14px 112px!important}.govo-os .govo-os-rail{display:none!important}html body.govo-os.govo-role-menu-open .govo-os-rail{display:block!important;left:12px!important;top:12px;bottom:12px;width:min(300px,calc(100vw - 48px));z-index:10002}.govo-os.govo-role-menu-open .govo-os-backdrop{display:block;position:fixed;inset:0;background:#020a0faf;z-index:10001}.govo-os.govo-role-menu-open{overflow:hidden}.govo-os .os-close{display:block;margin:0 0 16px auto;width:40px!important;padding:0!important}.govo-os .govo-os-dock{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr));gap:3px;position:fixed;bottom:max(10px,env(safe-area-inset-bottom));left:50%;transform:translateX(-50%);width:min(540px,calc(100% - 20px));border-radius:22px;padding:7px;background:color-mix(in srgb,var(--os-panel) 94%,transparent);backdrop-filter:blur(18px);border:1px solid var(--os-line);z-index:9999}.govo-os-dock a{display:flex;flex-direction:column;align-items:center;justify-content:center;text-decoration:none;color:var(--os-muted)!important;border-radius:14px;gap:5px;padding:7px 2px;font-size:10px;font-weight:800;min-height:58px;border:1px solid transparent}.govo-os-dock .govo-v32-glyph{width:28px;height:28px}.govo-os-workspace strong{font-size:20px}.govo-os-launcher{padding:0 12px 12px}.govo-os-launcher summary{padding:14px 0}.govo-os-apps a{min-height:105px!important;font-size:12px!important}.govo-os .govo-os-apps .govo-v32-glyph{width:56px!important;height:56px!important;min-width:56px!important;min-height:56px!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .govo-v28-header{padding:14px 0!important}.govo-os .govo-os-workspace{padding-bottom:14px}.govo-os-auth .govo-os-dock{display:none!important}}
@media(max-width:599px){html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(.grid,.grid.two,.stats-grid){grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important}.govo-os .grid>.card:not(.stat){grid-column:1/-1}.govo-os .stat{padding:14px!important}.govo-os .stat p{font-size:11px}.govo-os .stat .value{font-size:26px!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] :is(.detail-grid,.item-grid,.filters,.govo-form-grid){grid-template-columns:minmax(0,1fr)!important}.govo-os .three{grid-template-columns:repeat(3,minmax(0,1fr))!important}.govo-os .three button{font-size:12px!important;padding:10px 5px!important}html body.govo-os.govo-v32-ui[data-govo-os-role][data-govo-os-version] .card{padding:16px!important}.govo-os .actions .btn{width:auto!important;flex:1 1 130px}.govo-os .govo-role-actions :is(a,button){width:38px!important;min-width:38px!important;min-height:38px!important;padding:0!important}.govo-os .govo-master-copy strong{font-size:13px!important}.govo-os .govo-master-copy small{font-size:7px!important}.govo-os .govo-master-mark{width:44px!important;height:36px!important}}
@media(prefers-reduced-motion:reduce){.govo-os *{scroll-behavior:auto!important;transition:none!important}}
`;
const RUNTIME = `<script id="govo-role-os-runtime">document.addEventListener('DOMContentLoaded',function(){
 var body=document.body,rail=document.querySelector('.govo-os-rail'),menu=document.querySelector('.govo-role-actions button[aria-label="Menu"]');
 if(!rail)return;
 function state(){if(menu){menu.setAttribute('aria-expanded',String(body.classList.contains('govo-role-menu-open')));menu.setAttribute('aria-controls','govo-os-navigation');}}
 function close(){body.classList.remove('govo-role-menu-open');state();}
 if(menu){menu.removeAttribute('onclick');menu.addEventListener('click',function(){body.classList.toggle('govo-role-menu-open');state();});state();}
 document.querySelectorAll('[data-os-close]').forEach(function(b){b.addEventListener('click',function(){close();if(menu)menu.focus();});});
 document.addEventListener('keydown',function(e){if(e.key==='Escape'&&body.classList.contains('govo-role-menu-open')){close();if(menu)menu.focus();}});
 rail.addEventListener('keydown',function(e){if(e.key!=='Tab'||innerWidth>=1000||!body.classList.contains('govo-role-menu-open'))return;var items=[...rail.querySelectorAll('a,button')].filter(x=>x.getClientRects().length),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
 if(menu)menu.addEventListener('click',function(){if(body.classList.contains('govo-role-menu-open'))rail.querySelector('button,a').focus();});
 function active(){document.querySelectorAll('.govo-os-rail a,.govo-os-dock a').forEach(function(a){var u=new URL(a.href,location.href),matches=u.origin===location.origin&&u.pathname===location.pathname&&(u.hash?u.hash===location.hash:!location.hash);if(matches)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}active();window.addEventListener('hashchange',active);
 rail.querySelectorAll('a').forEach(function(a){a.addEventListener('click',close);});
 if(body.dataset.govoOsDashboard==='true'){
  var app=document.querySelector('main.app'),footer=app&&app.querySelector(':scope > .footer');
  if(app&&footer){
   if(body.dataset.govoOsRole!=='admin'){[...app.children].filter(e=>e.id==='profile'||['Product / Menu','Current Menu'].includes(e.querySelector('h2')?.textContent||'')).forEach(e=>app.insertBefore(e,footer));}
   else {var alerts=[...app.children].find(e=>e.querySelector('h2')?.textContent==='Alerts'),hero=app.querySelector(':scope > .hero');if(alerts&&hero)hero.after(alerts);}
  }
 }
 document.querySelectorAll('table').forEach(function(t){if(t.closest('.table-wrap,.govo-os-table'))return;var w=document.createElement('div');w.className='govo-os-table';w.tabIndex=0;w.setAttribute('role','region');w.setAttribute('aria-label','Scrollable data table');t.parentNode.insertBefore(w,t);w.appendChild(t);});
});</script>`;
function roleShell(html,role,title,options={}){
 const cfg=CONFIG[role];if(!cfg||typeof html!=='string'||!/<body\b/i.test(html)||html.includes('id="govo-role-os-style"'))return html;
 const auth=/login|password|registration|onboarding|unauthorized|account create/i.test(title)||/class=['"][^'"]*govo-role-auth/.test(html)||/<form\b[^>]*action=["'][^"']*\/(?:rider|merchant|admin)\/login(?:["'?\s])/i.test(html);
 const links=auth?(role==='admin'?[['Admin login','/admin/login','shield']]:[['Sign in',`/${role}/login`,'account'],['Join GOVO',`/${role}/onboarding`,role==='rider'?'ride':'shops'],['Application status',`/dashboard/${role}`,'shield']]):cfg.links;
 const rail=`<aside class="govo-os-rail" id="govo-os-navigation" aria-label="${cfg.label} workspace navigation"><button type="button" class="secondary os-close" data-os-close aria-label="Close menu">×</button><div class="os-rail-title">${cfg.label} workspace<small>GOVO EXPRESS</small></div><nav>${links.map(x=>link(x)).join('')}</nav>${auth?'':`<nav class="os-secondary" aria-label="More workspace tools">${cfg.extra.map(x=>link(x)).join('')}</nav>`}</aside><div class="govo-os-backdrop" data-os-close></div>`;
 const dashboard=/^(Merchant Dashboard|Rider Dashboard|Admin OS)$/.test(title)&&!auth;
 const workspace=auth?'':`<section class="govo-os-workspace" aria-label="Current workspace"><div><span class="os-eyebrow">GOVO / ${cfg.label} workspace</span><strong>${esc(title)}</strong><p>${cfg.hint}</p></div></section>${auth?'':`<details class="govo-os-launcher"${dashboard?' open':''}><summary>Workspace shortcuts</summary><nav class="govo-os-apps" aria-label="${cfg.label} shortcuts">${cfg.links.map(x=>link(x)).join('')}</nav></details>`}`;
 const dockLinks=role==='admin'?[cfg.links[0],cfg.links[1],cfg.links[2],cfg.links[7],cfg.links[8]]:role==='merchant'?[cfg.links[0],cfg.links[1],cfg.links[2],cfg.links[3],cfg.links[5]]:[cfg.links[0],cfg.links[1],cfg.links[2],cfg.links[3],cfg.links[6]];
 const dock=`<nav class="govo-os-dock" aria-label="${cfg.label} primary navigation">${dockLinks.map(x=>link(x)).join('')}</nav>`;
 html=html.replace(/<body([^>]*)>/i,(all,attrs)=>`<body data-govo-os-role="${role}" data-govo-os-version="34" data-govo-os-dashboard="${dashboard}"${/class=/.test(attrs)?attrs.replace(/class=(["'])(.*?)\1/i,(_,q,c)=>`class=${q}${c} govo-os govo-v32-ui ${auth?'govo-os-auth':''}${q}`):`${attrs} class="govo-os govo-v32-ui ${auth?'govo-os-auth':''}"`}>`);
 if(options.header){html=html.replace(/<header\b[\s\S]*?<\/header>/i,options.header);if(!/<header\b/i.test(html))html=html.replace(/<main[^>]*>/,m=>m+options.header);}
 html=html.replace('</head>',`<style id="govo-role-os-style">${CSS}</style></head>`);
 html=html.replace(/<\/header>/i,`</header>${rail}${workspace}`);
 return html.replace('</body>',`${auth?'':dock}${patternMarkup()}${RUNTIME}</body>`);
}
module.exports={roleShell,CONFIG,CSS};
