
const MOBILE_UX_CSS = `
.v20-shell{padding-bottom:calc(112px + env(safe-area-inset-bottom,0px))!important}
.v20-bottom{bottom:calc(10px + env(safe-area-inset-bottom,0px))!important}
.v20-icon-btn,.v23-close{min-width:44px;min-height:44px}
.v20-section>a{display:inline-flex;align-items:center;min-height:44px;padding:0 8px}
.v20-shell :is(input,select,textarea){font-size:16px!important;min-height:44px}
.v20-search button{min-width:44px;min-height:44px;cursor:pointer}
.v20-shell :is(a,button,input,select,textarea):focus-visible,.v20-bottom a:focus-visible,.v23-settings button:focus-visible{outline:3px solid var(--brand2);outline-offset:3px}
.v20-search:focus-within{border-color:var(--brand2)}
.v22-shop-card b,.v22-provider b,.v20-row-link b{overflow-wrap:anywhere}
.v23-settings{padding-bottom:calc(12px + env(safe-area-inset-bottom,0px))}
@media(max-width:360px){.v23-options{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){.v20-shell *,.v20-bottom *,.v23-settings *{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
const THEME=require('./govo_v20_theme');
const {icon}=require('./govo_v20_icons');
const {SETTINGS_MARKUP,SETTINGS_SCRIPT}=require('./govo_v23_settings');
const {renderHeader}=require('./govo_header_v28');
const {ICON_CSS,glossyIcon}=require('./govo_glossy_icons_v30');
const HOME_CSS=require('./govo_home_v30_css');
const logo='/uploads/govo-logo.png';
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function shell(title,active,body){
 const homeSurface=active==='home'||active==='more';
 const polished=true;
 const navIcon=k=>polished?glossyIcon(k==='home'?'home_nav':k):icon(k);
 const nav=[['home','Home','/app'],['shops','Shops','/shops'],['ai','GOVO AI','/ai'],['services','Services','/services'],['account','Account','/account']];
 const header=renderHeader({role:'customer',surface:'v20',logo:`<img src="${logo}" alt="GOVO">`,actions:`<a class="v20-icon-btn" href="/account#notifications" aria-label="Notifications">${icon('bell')}${polished?'':'<span class="v20-badge">3</span>'}</a><a class="v20-icon-btn" href="/more" aria-label="Menu">${icon('menu')}</a>`});
 const desktopNav=`<nav class="v20-desktop-nav" aria-label="Main navigation">${nav.map(([k,l,h])=>`<a class="${active===k?'active':''}" href="${h}"${active===k?' aria-current="page"':''}>${k==='ai'?'<img src="'+logo+'" alt="">':navIcon(k)}<span>${l}</span></a>`).join('')}</nav>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#00110c"><title>${esc(title)} — GOVO Express</title><style>${THEME}${ICON_CSS}${homeSurface?HOME_CSS:''}${MOBILE_UX_CSS}</style></head><body class="v20-page-${active}"><div class="v20-shell">${header}${desktopNav}${body}</div><nav class="v20-bottom" aria-label="Main navigation">${nav.map(([k,l,h])=>`<a class="v20-nav ${active===k?'active':''} ${k==='ai'?'v20-ai':''}" href="${h}"${active===k?' aria-current="page"':''}>${k==='ai'?`<span class="v20-ai-orb"><img src="${logo}" alt=""></span>`:navIcon(k)}<span>${l}</span></a>`).join('')}</nav>${SETTINGS_MARKUP}${SETTINGS_SCRIPT}</body></html>`;
}
function action(name,label,href,badge=''){return `<a class="v22-action" href="${href}">${badge?`<em>${esc(badge)}</em>`:''}<span class="v22-iconbox">${glossyIcon(name)}</span><span>${esc(label)}</span></a>`}
function shopCard(x){const t=x.shop_name||'Local Shop', area=x.shop_address||x.location||'Meherpur';return `<a class="v22-shop-card" href="/shop/${encodeURIComponent(x.id)}"><div class="v22-shop-cover">${esc(t.slice(0,1).toUpperCase())}</div><div class="v22-pad"><b>${esc(t)}</b><small>${esc((x.category||'Local shop')+' · '+area)}</small><div class="v22-meta"><span>View shop</span><span aria-hidden="true">→</span></div></div></a>`}
function providerCard(x){const t=x.provider_name||x.service_type||'Service Provider';return `<a class="v22-provider" href="/service/${encodeURIComponent(x.id)}"><span class="avatar">${esc(t.slice(0,1).toUpperCase())}</span><b>${esc(t)}</b><small>${esc(x.service_type||'Trusted service')}</small><div class="v22-meta"><span>View service</span><span aria-hidden="true">→</span></div></a>`}
const categories=[['food','Food','food'],['grocery','Grocery','grocery'],['pharmacy','Pharmacy','medicine'],['electronics','Electronics','electronics'],['fashion','Fashion','fashion'],['home','Home','home'],['beauty','Beauty','beauty'],['auto','Auto','auto'],['education','Education','education']];
function categoryCard(n,t,c){return `<a class="v30-category" href="/shops?category=${c}"><span class="v30-tile">${glossyIcon(n)}</span><b>${t}</b></a>`;}
function homePage(opts={}){const shops=opts.shops||[],providers=opts.providers||[];return shell('Home','home',`
<div class="v22-location"><span>${icon('location')} Meherpur, Bangladesh</span><a href="/more" aria-label="Explore local services">Explore ${icon('menu')}</a></div>
<section class="v20-hero v22-hero"><h1>Everything local.<em>One GOVO.</em></h1><p>Find local shops, book a service or arrange a delivery.</p><form method="GET" action="/shops"><div class="v20-search">${icon('search')}<input name="q" type="search" enterkeyhint="search" aria-label="Search local shops" placeholder="Search shops, products or areas..."><button type="submit" aria-label="Search">${icon('search')}</button></div></form></section>
<section class="v30-shortcuts" aria-labelledby="shortcut-title"><div class="v20-section"><h2 id="shortcut-title">What do you need?</h2></div><div class="v22-action-grid">${action('delivery','Delivery','/delivery')}${action('shops','Shops','/shops')}${action('services','Services','/services')}${action('home_service','Home Service','/home-service')}${action('ride','Ride','/ride')}${action('track','Track','/track')}${action('ai','AI Assistant','/ai')}${action('support','Help & Support','/support')}${action('more','More','/more')}</div></section>
<div class="v20-section"><h2>Popular Categories</h2><a href="/more#categories">View all</a></div><div class="v30-category-grid">${categories.slice(0,8).map(x=>categoryCard(...x)).join('')}<a class="v30-category" href="/more#categories"><span class="v30-tile">${glossyIcon('more')}</span><b>More</b></a></div>
<div class="v20-section"><h2>Featured Shops</h2><a href="/shops?type=shops">View all</a></div>${shops.length?`<div class="v22-card-scroll">${shops.slice(0,6).map(shopCard).join('')}</div>`:`<div class="v20-card"><b>Shops are opening soon</b><span>Approved merchants will appear here automatically.</span></div>`}
<div class="v20-section"><h2>Trusted Service Providers</h2><a href="/shops?type=services">View all</a></div>${providers.length?`<div class="v22-provider-grid">${providers.slice(0,6).map(providerCard).join('')}</div>`:`<div class="v20-card"><b>Providers are being verified</b><span>Trusted services will appear here automatically.</span></div>`}
<a class="v22-banner" href="/refer"><div><h3>Refer & Earn</h3><p>Invite friends and earn exciting rewards</p></div><div class="gift">🎁</div></a>
<div class="v20-section"><h2>How GOVO Works</h2><a href="/more">View all</a></div><div class="v22-steps"><div class="v22-step"><span>1</span><b>Search</b><small>Find what you need</small></div><div class="v22-step"><span>2</span><b>Choose</b><small>Pick the best option</small></div><div class="v22-step"><span>3</span><b>Order/Request</b><small>Place order or request</small></div><div class="v22-step"><span>4</span><b>Get it Done</b><small>We deliver or complete</small></div></div>
<div class="v20-section"><h2>Why Choose GOVO</h2></div><div class="v22-trust-grid"><div class="v22-trust"><b>✓ Verified & Trusted</b><small>Only verified shops & providers</small></div><div class="v22-trust"><b>◈ Secure & Safe</b><small>Protected customer data</small></div><div class="v22-trust"><b>⚡ Fast & Reliable</b><small>Quick delivery & support</small></div></div>
<a class="v22-banner" href="/service-request"><div><h3>Need something specific?</h3><p>Request anything, we’ll try our best to get it for you.</p></div><div class="gift">🛍️</div></a>`)}
function popular(name,title,desc,href){return `<a class="v22-popular" href="${href}">${icon(name)}<b>${title}</b><small>${desc}</small></a>`}
function aiPage(q=''){const query=String(q||'').trim();const s=['Best pharmacy near me','Grocery delivery in Meherpur','Home cleaning service','Book a delivery','Track my order','Emergency help'];return shell('GOVO AI Assistant','ai',`<section class="v22-page-title"><h1>GOVO AI Assistant</h1><p>Your smart helper for shops, services, delivery & support.</p></section><form class="v22-ai-search" method="GET" action="/ai">${icon('search')}<input name="q" type="search" enterkeyhint="search" aria-label="Ask GOVO AI" value="${esc(query)}" placeholder="Ask me anything..."><button class="v22-mic" type="submit">${icon('ai')}</button></form>${query?`<div class="v20-card" style="margin-top:12px"><b>${esc(query)}</b><span>Search marketplace results or send a custom request.</span><div class="v20-actions"><a class="v20-btn" href="/shops?q=${encodeURIComponent(query)}">Search</a><a class="v20-btn secondary" href="/service-request?service_type=${encodeURIComponent(query)}">Request</a></div></div>`:''}<div class="v20-section"><h2>Try these</h2></div><div class="v22-suggestions">${s.map(x=>`<a href="/ai?q=${encodeURIComponent(x)}">${esc(x)}</a>`).join('')}</div><div class="v20-section"><h2>Popular Actions</h2></div><div class="v22-popular-grid">${popular('shops','Find Shop','Search shops, products & more','/shops')}${popular('services','Find Service','Find trusted service providers','/services')}${popular('delivery','Book Delivery','Parcel, food, medicine & more','/delivery')}${popular('track','Track Order','Track your order in real time','/track')}${popular('support','Human Support','Call / WhatsApp support','/support')}${popular('requests','Report an Issue','Help us improve GOVO','/support')}</div><div class="v20-section"><h2>Example Questions</h2></div><div class="v20-row-stack">${s.slice(0,4).map(x=>`<a class="v20-row-link" href="/ai?q=${encodeURIComponent(x)}"><span>${icon('search')}</span><span><b>${esc(x)}</b></span><strong>›</strong></a>`).join('')}</div>`)}
function row(name,title,desc,href,tone=''){return `<a class="v20-row-link ${tone}" href="${href}"><span class="v20-row-icon">${icon(name)}</span><span><b>${title}</b><small>${desc}</small></span><strong>›</strong></a>`}
function accountPage(){return shell('Account','account',`<section class="v22-account-guest"><span class="avatar">${icon('account')}</span><div><h2>Welcome to GOVO</h2><p>Sign in / Create account to manage your orders, requests and payments.</p></div><div class="v22-auth-actions"><a href="/login">Sign In</a><a class="secondary" href="/register">Create Account</a></div></section><section class="v22-group"><h2>My Account</h2>${row('account','My Profile','Personal information','/profile')}${row('location','Addresses','Manage saved addresses','/addresses')}${row('payment','Payment Methods','Cards, wallets & more','/payments')}${row('orders','My Orders','View your orders','/track')}${row('requests','My Requests','View your service requests','/track?type=service')}${row('track','Track Orders','Track your orders','/track')}</section><section class="v22-group"><h2>Preferences</h2>${row('bell','Notifications','Manage your notifications','#notifications')}${row('language','Language','English · বাংলা · Banglish','#language')}${row('theme','Theme','System · Dark · Light','#theme')}</section><section class="v22-group"><h2>Support & More</h2>${row('support','Help & Support','Get help & contact support','/support')}${row('gift','Refer & Earn','Invite friends & earn rewards','/refer')}${row('shield','About GOVO Express','Version 2.0.0','/about')}${row('shield','Privacy Policy','Your privacy matters','/privacy')}${row('requests','Terms & Conditions','Read our terms','/terms')}</section>`)}
function morePage(){const i=[['delivery','Delivery','/delivery'],['shops','Shops','/shops'],['services','Services','/services'],['home_service','Home Service','/home-service'],['ride','Ride','/ride'],['track','Track','/track'],['ai','AI Assistant','/ai'],['doctor','Doctor','/doctor'],['agri','Agriculture','/agri'],['account','Account','/account'],['support','Help & Support','/support'],['requests','Request Help','/service-request']];return shell('More Services','more',`<a class="v30-back" href="/app">← Back to Home</a><section class="v22-page-title"><h1>Explore GOVO</h1><p>Choose a service or browse your local shops.</p></section><div class="v22-action-grid">${i.map(([n,t,h])=>action(n,t,h)).join('')}</div><div class="v20-section" id="categories"><h2>All Categories</h2></div><div class="v30-category-grid">${categories.map(x=>categoryCard(...x)).join('')}<a class="v30-category" href="/shops"><span class="v30-tile">${glossyIcon('shops')}</span><b>All Shops</b></a></div>`)}
function app(){return homePage({})}function generic(name,active,desc){return shell(name,active,`<section class="v20-hero"><h1>${esc(name)}</h1><p>${esc(desc)}</p></section>`)}function render(page,opts){if(page==='app')return homePage(opts||{});if(page==='ai')return aiPage((opts||{}).q||'');if(page==='account')return accountPage();if(page==='more')return morePage();return generic(page,'home','GOVO Express')}
module.exports={render,shell,homePage,aiPage,accountPage,morePage};
